import type { NewRoute } from "./schema";

type SeedRoute = Omit<NewRoute, "status" | "id" | "createdAt" | "updatedAt">;

export const seedRoutes: SeedRoute[] = [
  {
    slug: "tbilisi-kojori",
    title: "Tbilisi to Kojori",
    startName: "Tbilisi",
    endName: "Kojori",
    region: "Tbilisi",
    distanceKm: 42,
    durationMin: 60,
    scenery: 9,
    roadQuality: 7,
    difficulty: "moderate",
    bestFor: ["coupes", "mountain views", "quiet drives"],
    bestTime: "Sunset or night",
    description: "Climb out of the city through Tskneti to the Kojori plateau, with the lights of Tbilisi below.",
    notes: "Best at sunset or at night.",
    path: [[41.694, 44.801], [41.69, 44.75], [41.694, 44.7], [41.664, 44.708]],
    stops: [{ name: "Tskneti viewpoint", type: "viewpoint", lat: 41.694, lng: 44.7 }],
    featured: true,
  },
  {
    slug: "georgian-military-road",
    title: "Georgian Military Road",
    startName: "Tbilisi",
    endName: "Stepantsminda",
    region: "Mtskheta-Mtianeti",
    distanceKm: 155,
    durationMin: 180,
    scenery: 10,
    roadQuality: 7,
    difficulty: "challenging",
    bestFor: ["mountain views", "long drives"],
    bestTime: "Late evening in summer",
    description: "The classic drive north past Ananuri fortress and over the Jvari Pass to Kazbegi.",
    notes: "Check pass conditions in winter.",
    path: [[41.694, 44.801], [41.845, 44.72], [42.164, 44.703], [42.478, 44.479], [42.657, 44.643]],
    stops: [
      { name: "Ananuri fortress", type: "viewpoint", lat: 42.164, lng: 44.703 },
      { name: "Gudauri fuel", type: "fuel", lat: 42.478, lng: 44.479 },
    ],
    featured: true,
  },
  {
    slug: "gombori-pass",
    title: "Gombori Pass to Sighnaghi",
    startName: "Tbilisi",
    endName: "Sighnaghi",
    region: "Kakheti",
    distanceKm: 160,
    durationMin: 200,
    scenery: 9,
    roadQuality: 6,
    difficulty: "moderate",
    bestFor: ["forest roads", "wine country"],
    bestTime: "Evening",
    description: "Wind over the forested Gombori Pass to Telavi, then along the Alazani valley to Sighnaghi.",
    notes: null,
    path: [[41.694, 44.801], [41.85, 45.2], [41.92, 45.473], [41.62, 45.922]],
    stops: [{ name: "Telavi café", type: "cafe", lat: 41.92, lng: 45.473 }],
    featured: false,
  },
  {
    slug: "batumi-sarpi",
    title: "Batumi to Sarpi coast road",
    startName: "Batumi",
    endName: "Sarpi",
    region: "Adjara",
    distanceKm: 18,
    durationMin: 30,
    scenery: 8,
    roadQuality: 8,
    difficulty: "easy",
    bestFor: ["sea views", "short drives"],
    bestTime: "Night",
    description: "A short coastal run south from Batumi, hugging the Black Sea cliffs to the Turkish border.",
    notes: null,
    path: [[41.617, 41.637], [41.57, 41.58], [41.521, 41.548]],
    stops: [],
    featured: true,
  },
  {
    slug: "borjomi-bakuriani",
    title: "Borjomi to Bakuriani",
    startName: "Borjomi",
    endName: "Bakuriani",
    region: "Samtskhe-Javakheti",
    distanceKm: 30,
    durationMin: 50,
    scenery: 8,
    roadQuality: 7,
    difficulty: "moderate",
    bestFor: ["forest roads", "mountain views"],
    bestTime: "Evening",
    description: "Pine forest switchbacks from the spa town of Borjomi up to the ski resort of Bakuriani.",
    notes: null,
    path: [[41.839, 43.379], [41.8, 43.45], [41.75, 43.53]],
    stops: [],
    featured: false,
  },
  {
    slug: "tbilisi-night-loop",
    title: "Tbilisi night loop",
    startName: "Turtle Lake",
    endName: "Tbilisi Sea",
    region: "Tbilisi",
    distanceKm: 25,
    durationMin: 40,
    scenery: 7,
    roadQuality: 8,
    difficulty: "easy",
    bestFor: ["city lights", "short drives"],
    bestTime: "Late night",
    description: "A relaxed loop from Turtle Lake across the city to the Tbilisi Sea.",
    notes: null,
    path: [[41.693, 44.761], [41.72, 44.79], [41.755, 44.82]],
    stops: [{ name: "Tbilisi Sea parking", type: "parking", lat: 41.755, lng: 44.82 }],
    featured: false,
  },
  {
    slug: "kutaisi-martvili",
    title: "Kutaisi to Martvili",
    startName: "Kutaisi",
    endName: "Martvili",
    region: "Imereti",
    distanceKm: 55,
    durationMin: 75,
    scenery: 7,
    roadQuality: 6,
    difficulty: "easy",
    bestFor: ["quiet drives", "countryside"],
    bestTime: "Evening",
    description: "Rolling countryside west from Kutaisi to the Martvili canyon area.",
    notes: null,
    path: [[42.268, 42.695], [42.34, 42.54], [42.414, 42.379]],
    stops: [],
    featured: false,
  },
  {
    slug: "zugdidi-mestia",
    title: "Zugdidi to Mestia",
    startName: "Zugdidi",
    endName: "Mestia",
    region: "Samegrelo-Zemo Svaneti",
    distanceKm: 135,
    durationMin: 180,
    scenery: 10,
    roadQuality: 6,
    difficulty: "challenging",
    bestFor: ["mountain views", "long drives"],
    bestTime: "Dusk",
    description: "Past the Enguri dam and up the gorge into Svaneti.",
    notes: "Rockfall is possible after rain.",
    path: [[42.509, 41.871], [42.717, 42.05], [42.9, 42.4], [43.045, 42.729]],
    stops: [{ name: "Enguri dam viewpoint", type: "viewpoint", lat: 42.717, lng: 42.05 }],
    featured: false,
  },
  {
    slug: "tbilisi-mtskheta",
    title: "Tbilisi to Mtskheta and Jvari",
    startName: "Tbilisi",
    endName: "Jvari Monastery",
    region: "Mtskheta-Mtianeti",
    distanceKm: 25,
    durationMin: 35,
    scenery: 8,
    roadQuality: 8,
    difficulty: "easy",
    bestFor: ["history", "short drives"],
    bestTime: "Night",
    description: "Up the river to the old capital and the hilltop monastery over the confluence.",
    notes: null,
    path: [[41.694, 44.801], [41.78, 44.77], [41.845, 44.72], [41.838, 44.734]],
    stops: [],
    featured: false,
  },
];
